function dolatextable(filename,cohort,Ni,cell_demog,cell_outcome,cell_icd9,cell_elix,cell_elix_pt,cell_scores,cell_treats,cell_labs)

FID = fopen(filename, 'w');
fprintf(FID, '\\caption{%s}\n',sprintf('Proportional characteristics of %s patients (n = %d).',cohort,sum(Ni)));
fprintf(FID, '\\centerline{\\small \n');
fprintf(FID, '\\begin{tabular}{l r l c r l c}\n');
fprintf(FID, '\\toprule\n');
%fprintf(FID, '& \\multicolumn{5}{c}{\\textbf{No. (\\%%) [95\\%% CI] of Patients}} & \\\\ \n');
%fprintf(FID, '\\cmidrule(l){2-6} \n');
fprintf(FID, '& \\multicolumn{2}{c}{Normal} & ~~~ & \\multicolumn{2}{c}{Hyperdynamic} & P \\\\ \n');
fprintf(FID, '& \\multicolumn{2}{c}{(n=%d , %d\\%%)} & & \\multicolumn{2}{c}{(n=%d, %d\\%%)} & value \\\\ \n',Ni(1),round(Ni(1)/sum(Ni)*100),Ni(2),round(Ni(2)/sum(Ni)*100));
fprintf(FID, '\\hline\n');

%demog_labels = {'AGE', 'MALE', 'MICU', 'CCU', 'SICU', 'CSRU','FICU'};
if cell_demog{2,4} < 0.001
    fprintf(FID, '%s & %d & (%d) & & %d & (%d) & $\\mathbf{<0.001}$ \\\\ \n',cell_demog{2,1}, ...
        cell_demog{2,2}(1), round(cell_demog{2,2}(2)), ...
        cell_demog{2,3}(1), round(cell_demog{2,3}(2)));
elseif cell_demog{2,4} <= 0.05
    fprintf(FID, '%s & %d & (%d) & & %d & (%d) & \\textbf{%.3f} \\\\ \n',cell_demog{2,1}, ...
        cell_demog{2,2}(1), round(cell_demog{2,2}(2)), ...
        cell_demog{2,3}(1), round(cell_demog{2,3}(2)), ...
        cell_demog{2,4});
else
    fprintf(FID, '%s & %d & (%d) & & %d & (%d) & %.3f \\\\ \n',cell_demog{2,1}, ...
        cell_demog{2,2}(1), round(cell_demog{2,2}(2)), ...
        cell_demog{2,3}(1), round(cell_demog{2,3}(2)), ...
        cell_demog{2,4});
end
fprintf(FID, 'Service type: & & & & & & \\\\ \n');
for i = 1 : 4
    if cell_demog{2+i,2}(1) == 0 && cell_demog{2+i,3}(1) == 0
        fprintf(FID, '%s & 0 & (0) & & 0 & (0) & NA \\\\ \n',cell_demog{2+i,1});
    elseif cell_demog{2+i,4} < 0.001
        fprintf(FID, '%s & %d & (%d) & & %d & (%d) & $\\mathbf{<0.001}$ \\\\ \n',cell_demog{2+i,1}, ...
            cell_demog{2+i,2}(1), round(cell_demog{2+i,2}(2)), ...
            cell_demog{2+i,3}(1), round(cell_demog{2+i,3}(2)));
    elseif cell_demog{2+i,4} <= 0.05
        fprintf(FID, '%s & %d & (%d) & & %d & (%d) & \\textbf{%.3f} \\\\ \n',cell_demog{2+i,1}, ...
            cell_demog{2+i,2}(1), round(cell_demog{2+i,2}(2)), ...
            cell_demog{2+i,3}(1), round(cell_demog{2+i,3}(2)), ...
            cell_demog{2+i,4});
    else
        fprintf(FID, '%s & %d & (%d) & & %d & (%d) & %.3f \\\\ \n',cell_demog{2+i,1}, ...
            cell_demog{2+i,2}(1), round(cell_demog{2+i,2}(2)), ...
            cell_demog{2+i,3}(1), round(cell_demog{2+i,3}(2)), ...
            cell_demog{2+i,4});
    end
end


%outcomes = {'ICU_LOS','HOSP_LOS','MORTALITY_28D','ONE_YEAR_MORTALITY',...
%    'ICUSTAY_MORTALITY','HOSPITAL_MORTALITY'};
fprintf(FID, 'Primary outcomes: & & & & & & \\\\ \n');
for i = 3 : 6
    if cell_outcome{i,4} < 0.001
        fprintf(FID, '%s & %d & (%d) & & %d & (%d) & $\\mathbf{<0.001}$ \\\\ \n',cell_outcome{i,1}, ...
            cell_outcome{i,2}(1), round(cell_outcome{i,2}(2)), ...
            cell_outcome{i,3}(1), round(cell_outcome{i,3}(2)));
    elseif cell_outcome{i,4} <= 0.05
        fprintf(FID, '%s & %d & (%d) & & %d & (%d) & \\textbf{%.3f} \\\\ \n',cell_outcome{i,1}, ...
            cell_outcome{i,2}(1), round(cell_outcome{i,2}(2)), ...
            cell_outcome{i,3}(1), round(cell_outcome{i,3}(2)), ...
            cell_outcome{i,4});
    else
        fprintf(FID, '%s & %d & (%d) & & %d & (%d) & %.3f \\\\ \n',cell_outcome{i,1}, ...
            cell_outcome{i,2}(1), round(cell_outcome{i,2}(2)), ...
            cell_outcome{i,3}(1), round(cell_outcome{i,3}(2)), ...
            cell_outcome{i,4});
    end
end

%treatments = {'RRT','VASOPRESSORS','VENTILATED','FLUIDS_IN','FLUIDS_OUT',...
%              'MAX_PRESSOR_DOSE','MAX_PRESSOR_DURATION'};
fprintf(FID, 'Treatments: & & & & & & \\\\ \n');
for i = 1:3
    if cell_treats{i,4} < 0.001
        fprintf(FID, '%s & %d & (%d) & & %d & (%d) & $\\mathbf{<0.001}$ \\\\ \n',cell_treats{i,1}, ...
            cell_treats{i,2}(1), round(cell_treats{i,2}(2)), ...
            cell_treats{i,3}(1), round(cell_treats{i,3}(2)));
    elseif cell_treats{i,4} <= 0.05
        fprintf(FID, '%s & %d & (%d) & & %d & (%d) & \\textbf{%.3f} \\\\ \n',cell_treats{i,1}, ...
            cell_treats{i,2}(1), round(cell_treats{i,2}(2)), ...
            cell_treats{i,3}(1), round(cell_treats{i,3}(2)), ...
            cell_treats{i,4});
    else
        fprintf(FID, '%s & %d & (%d) & & %d & (%d) & %.3f \\\\ \n',cell_treats{i,1}, ...
            cell_treats{i,2}(1), round(cell_treats{i,2}(2)), ...
            cell_treats{i,3}(1), round(cell_treats{i,3}(2)), ...
            cell_treats{i,4});
    end
end

fprintf(FID, '\\bottomrule\n');
fprintf(FID, '\\end{tabular}\n');
fprintf(FID, '}\n');
fclose(FID);

%% File 2

FID = fopen(strcat(filename(1:end-4),'_median.tex'), 'w');
fprintf(FID, '\\caption{%s}\n',sprintf('Continuous characteristics of %s patients (n = %d).',cohort,sum(Ni)));
fprintf(FID, '\\centerline{\\small \n');
fprintf(FID, '\\begin{tabular}{l r l c r l c}\n');
fprintf(FID, '\\toprule\n');
%fprintf(FID, '& \\multicolumn{5}{c}{\\textbf{No. (\\%%) [95\\%% CI] of Patients}} & \\\\ \n');
%fprintf(FID, '\\cmidrule(l){2-6} \n');
fprintf(FID, '& \\multicolumn{2}{c}{Normal} & ~~~ & \\multicolumn{2}{c}{Hyperdynamic} & P \\\\ \n');
fprintf(FID, '& \\multicolumn{2}{c}{(n=%d, %d\\%%)} & & \\multicolumn{2}{c}{(n=%d, %d\\%%)} & value \\\\ \n',Ni(1),round(Ni(1)/sum(Ni)*100),Ni(2),round(Ni(2)/sum(Ni)*100));
fprintf(FID, '\\hline\n');

%demog_labels = {'AGE', 'MALE', 'MICU', 'CCU', 'SICU', 'CSRU','FICU'};
if cell_demog{1,4} < 0.001
    fprintf(FID, '%s & %.1f & (%.1f-%.1f) & & %.1f & (%.1f-%.1f) & $\\mathbf{<0.001}$ \\\\ \n',cell_demog{1,1}, ...
        cell_demog{1,2}(1), cell_demog{1,2}(2), cell_demog{1,2}(3), ...
        cell_demog{1,3}(1), cell_demog{1,3}(2), cell_demog{1,3}(3));
elseif cell_demog{1,4} <= 0.05
    fprintf(FID, '%s & %.1f & (%.1f-%.1f) & & %.1f & (%.1f-%.1f) & \\textbf{%.3f} \\\\ \n',cell_demog{1,1}, ...
        cell_demog{1,2}(1), cell_demog{1,2}(2), cell_demog{1,2}(3), ...
        cell_demog{1,3}(1), cell_demog{1,3}(2), cell_demog{1,3}(3), ...
        cell_demog{1,4});
else
    fprintf(FID, '%s & %.1f & (%.1f-%.1f) & & %.1f & (%.1f-%.1f) & %.3f \\\\ \n',cell_demog{1,1}, ...
        cell_demog{1,2}(1), cell_demog{1,2}(2), cell_demog{1,2}(3), ...
        cell_demog{1,3}(1), cell_demog{1,3}(2), cell_demog{1,3}(3), ...
        cell_demog{1,4});
end

%outcomes = {'ICU_LOS','HOSP_LOS','MORTALITY_28D','ONE_YEAR_MORTALITY',...
%    'ICUSTAY_MORTALITY','HOSPITAL_MORTALITY'};
fprintf(FID, 'Secondary outcomes: & & & & & & \\\\ \n');
for i = 1 : 2
    if cell_outcome{i,4} < 0.001
        fprintf(FID, '%s & %.1f & (%.1f-%.1f) & & %.1f & (%.1f-%.1f) & $\\mathbf{<0.001}$ \\\\ \n',cell_outcome{i,1}, ...
            cell_outcome{i,2}(1), (cell_outcome{i,2}(2)), (cell_outcome{i,2}(3)), ...
            cell_outcome{i,3}(1), (cell_outcome{i,3}(2)), (cell_outcome{i,3}(3)));
    elseif cell_outcome{i,4} <= 0.05
        fprintf(FID, '%s & %.1f & (%.1f-%.1f) & & %.1f & (%.1f-%.1f) & \\textbf{%.3f} \\\\ \n',cell_outcome{i,1}, ...
            cell_outcome{i,2}(1), (cell_outcome{i,2}(2)), (cell_outcome{i,2}(3)), ...
            cell_outcome{i,3}(1), (cell_outcome{i,3}(2)), (cell_outcome{i,3}(3)), ...
            cell_outcome{i,4});
    else
        fprintf(FID, '%s & %.1f & (%.1f-%.1f) & & %.1f & (%.1f-%.1f) & %.3f \\\\ \n',cell_outcome{i,1}, ...
            cell_outcome{i,2}(1), (cell_outcome{i,2}(2)), (cell_outcome{i,2}(3)), ...
            cell_outcome{i,3}(1), (cell_outcome{i,3}(2)), (cell_outcome{i,3}(3)), ...
            cell_outcome{i,4});
    end
end

%scores = {'SOFA','SOFA_D1','SOFA_D2','SOFA_D3','SAPS','SAPS_D1','SAPS_D2','SAPS_D3'};
fprintf(FID, 'SOFA Scores: & & & & & & \\\\ \n');
for i = 1 : 4
    if cell_scores{i,4} < 0.001
        fprintf(FID, '%s & %.1f & (%.1f-%.1f) & & %.1f & (%.1f-%.1f) & $\\mathbf{<0.001}$ \\\\ \n',cell_scores{i,1}, ...
            cell_scores{i,2}(1), (cell_scores{i,2}(2)), (cell_scores{i,2}(3)), ...
            cell_scores{i,3}(1), (cell_scores{i,3}(2)), (cell_scores{i,3}(3)));
    elseif cell_scores{i,4} <= 0.05
        fprintf(FID, '%s & %.1f & (%.1f-%.1f) & & %.1f & (%.1f-%.1f) & \\textbf{%.3f} \\\\ \n',cell_scores{i,1}, ...
            cell_scores{i,2}(1), (cell_scores{i,2}(2)), (cell_scores{i,2}(3)), ...
            cell_scores{i,3}(1), (cell_scores{i,3}(2)), (cell_scores{i,3}(3)), ...
            cell_scores{i,4});
    else
        fprintf(FID, '%s & %.1f & (%.1f-%.1f) & & %.1f & (%.1f-%.1f) & %.3f \\\\ \n',cell_scores{i,1}, ...
            cell_scores{i,2}(1), (cell_scores{i,2}(2)), (cell_scores{i,2}(3)), ...
            cell_scores{i,3}(1), (cell_scores{i,3}(2)), (cell_scores{i,3}(3)), ...
            cell_scores{i,4});
    end
end
fprintf(FID, 'SAPS-I Scores: & & & & & & \\\\ \n');
for i = 5 : 8
    if cell_scores{i,4} < 0.001
        fprintf(FID, '%s & %.1f & (%.1f-%.1f) & & %.1f & (%.1f-%.1f) & $\\mathbf{<0.001}$ \\\\ \n',cell_scores{i,1}, ...
            cell_scores{i,2}(1), (cell_scores{i,2}(2)), (cell_scores{i,2}(3)), ...
            cell_scores{i,3}(1), (cell_scores{i,3}(2)), (cell_scores{i,3}(3)));
    elseif cell_scores{i,4} <= 0.05
        fprintf(FID, '%s & %.1f & (%.1f-%.1f) & & %.1f & (%.1f-%.1f) & \\textbf{%.3f} \\\\ \n',cell_scores{i,1}, ...
            cell_scores{i,2}(1), (cell_scores{i,2}(2)), (cell_scores{i,2}(3)), ...
            cell_scores{i,3}(1), (cell_scores{i,3}(2)), (cell_scores{i,3}(3)), ...
            cell_scores{i,4});
    else
        fprintf(FID, '%s & %.1f & (%.1f-%.1f) & & %.1f & (%.1f-%.1f) & %.3f \\\\ \n',cell_scores{i,1}, ...
            cell_scores{i,2}(1), (cell_scores{i,2}(2)), (cell_scores{i,2}(3)), ...
            cell_scores{i,3}(1), (cell_scores{i,3}(2)), (cell_scores{i,3}(3)), ...
            cell_scores{i,4});
    end
end

% labs = {'LACTATE','WBC','CREATENIN'};
fprintf(FID, 'Lab Tests (first 3 days): & & & & & & \\\\ \n');
for i = 1 : size(cell_labs,1)
    if cell_labs{i,4} < 0.001
        fprintf(FID, '%s & %.1f & (%.1f-%.1f) & & %.1f & (%.1f-%.1f) & $\\mathbf{<0.001}$ \\\\ \n',cell_labs{i,1}, ...
            cell_labs{i,2}(1), (cell_labs{i,2}(2)), (cell_labs{i,2}(3)), ...
            cell_labs{i,3}(1), (cell_labs{i,3}(2)), (cell_labs{i,3}(3)));
    elseif cell_labs{i,4} <= 0.05
        fprintf(FID, '%s & %.1f & (%.1f-%.1f) & & %.1f & (%.1f-%.1f) & \\textbf{%.3f} \\\\ \n',cell_labs{i,1}, ...
            cell_labs{i,2}(1), (cell_labs{i,2}(2)), (cell_labs{i,2}(3)), ...
            cell_labs{i,3}(1), (cell_labs{i,3}(2)), (cell_labs{i,3}(3)), ...
            cell_labs{i,4});
    else
        fprintf(FID, '%s & %.1f & (%.1f-%.1f) & & %.1f & (%.1f-%.1f) & %.3f \\\\ \n',cell_labs{i,1}, ...
            cell_labs{i,2}(1), (cell_labs{i,2}(2)), (cell_labs{i,2}(3)), ...
            cell_labs{i,3}(1), (cell_labs{i,3}(2)), (cell_labs{i,3}(3)), ...
            cell_labs{i,4});
    end
end

% elix_pt = {'ELIX_28D_PT','ELIX_1YR_PT','ELIX_2YR_PT'};
fprintf(FID, 'Elixhauser Points: & & & & & & \\\\ \n');
for i = 1 : size(cell_elix_pt,1)
    if cell_elix_pt{i,4} < 0.001
        fprintf(FID, '%s & %.1f & (%.1f-%.1f) & & %.1f & (%.1f-%.1f) & $\\mathbf{<0.001}$ \\\\ \n',cell_elix_pt{i,1}, ...
            cell_elix_pt{i,2}(1), (cell_elix_pt{i,2}(2)), (cell_elix_pt{i,2}(3)), ...
            cell_elix_pt{i,3}(1), (cell_elix_pt{i,3}(2)), (cell_elix_pt{i,3}(3)));
    elseif cell_elix_pt{i,4} <= 0.05
        fprintf(FID, '%s & %.1f & (%.1f-%.1f) & & %.1f & (%.1f-%.1f) & \\textbf{%.3f} \\\\ \n',cell_elix_pt{i,1}, ...
            cell_elix_pt{i,2}(1), (cell_elix_pt{i,2}(2)), (cell_elix_pt{i,2}(3)), ...
            cell_elix_pt{i,3}(1), (cell_elix_pt{i,3}(2)), (cell_elix_pt{i,3}(3)), ...
            cell_elix_pt{i,4});
    else
        fprintf(FID, '%s & %.1f & (%.1f-%.1f) & & %.1f & (%.1f-%.1f) & %.3f \\\\ \n',cell_elix_pt{i,1}, ...
            cell_elix_pt{i,2}(1), (cell_elix_pt{i,2}(2)), (cell_elix_pt{i,2}(3)), ...
            cell_elix_pt{i,3}(1), (cell_elix_pt{i,3}(2)), (cell_elix_pt{i,3}(3)), ...
            cell_elix_pt{i,4});
    end
end


%treatments = {'RRT','VASOPRESSORS','VENTILATED','FLUIDS_IN','FLUIDS_OUT',...
%              'MAX_PRESSOR_DOSE','MAX_PRESSOR_DURATION'};
fprintf(FID, 'Treatments (first 3 days): & & & & & & \\\\ \n');
for i = 4 : 7
    if cell_treats{i,4} < 0.001
        fprintf(FID, '%s & %.1f & (%.1f-%.1f) & & %.1f & (%.1f-%.1f) & $\\mathbf{<0.001}$ \\\\ \n',cell_treats{i,1}, ...
            cell_treats{i,2}(1), (cell_treats{i,2}(2)), (cell_treats{i,2}(3)), ...
            cell_treats{i,3}(1), (cell_treats{i,3}(2)), (cell_treats{i,3}(3)));
    elseif cell_treats{i,4} < 0.05
        fprintf(FID, '%s & %.1f & (%.1f-%.1f) & & %.1f & (%.1f-%.1f) & \\textbf{%.3f} \\\\ \n',cell_treats{i,1}, ...
            cell_treats{i,2}(1), (cell_treats{i,2}(2)), (cell_treats{i,2}(3)), ...
            cell_treats{i,3}(1), (cell_treats{i,3}(2)), (cell_treats{i,3}(3)), ...
            cell_treats{i,4});
    else
        fprintf(FID, '%s & %.1f & (%.1f-%.1f) & & %.1f & (%.1f-%.1f) & %.3f \\\\ \n',cell_treats{i,1}, ...
            cell_treats{i,2}(1), (cell_treats{i,2}(2)), (cell_treats{i,2}(3)), ...
            cell_treats{i,3}(1), (cell_treats{i,3}(2)), (cell_treats{i,3}(3)), ...
            cell_treats{i,4});
    end
end

fprintf(FID, '\\bottomrule\n');
fprintf(FID, '\\end{tabular}\n');
fprintf(FID, '}\n');
fclose(FID);

%% File 3

FID = fopen(strcat(filename(1:end-4),'_icd9.tex'), 'w');
fprintf(FID, '\\caption{%s}\n',sprintf('ICD9 Group and Elixhauser comorbidities of %s patients (n = %d).',cohort,sum(Ni)));
fprintf(FID, '\\centerline{\\small \n');
fprintf(FID, '\\begin{tabular}{l r l c r l c}\n');
fprintf(FID, '\\toprule\n');
%fprintf(FID, '& \\multicolumn{5}{c}{\\textbf{No. (\\%%) [95\\%% CI] of Patients}} & \\\\ \n');
%fprintf(FID, '\\cmidrule(l){2-6} \n');
fprintf(FID, '& \\multicolumn{2}{c}{Normal} & ~~~ & \\multicolumn{2}{c}{Hyperdynamic} & P \\\\ \n');
fprintf(FID, '& \\multicolumn{2}{c}{(n=%d , %d\\%%)} & & \\multicolumn{2}{c}{(n=%d, %d\\%%)} & value \\\\ \n',Ni(1),round(Ni(1)/sum(Ni)*100),Ni(2),round(Ni(2)/sum(Ni)*100));
fprintf(FID, '\\hline\n');

%icd9 = {'CARDIOVASCULAR','RESPIRATORY','CANCER','ENDOCRINE_METABOLIC',...
%        'GI','GU','TRAUMA','TREATMENT'};
fprintf(FID, 'ICD9 Group: & & & & & & \\\\ \n');
for i = 1 : size(cell_icd9)
    if cell_icd9{i,2}(1) == 0 && cell_icd9{i,3}(1) == 0
        fprintf(FID, '%s & 0 & (0) & & 0 & (0) & NA \\\\ \n',cell_icd9{i,1});
    elseif cell_icd9{i,4} < 0.001
        fprintf(FID, '%s & %d & (%d) & & %d & (%d) & $\\mathbf{<0.001}$ \\\\ \n',cell_icd9{i,1}, ...
            cell_icd9{i,2}(1), round(cell_icd9{i,2}(2)), ...
            cell_icd9{i,3}(1), round(cell_icd9{i,3}(2)));
    elseif cell_icd9{i,4} < 0.05
        fprintf(FID, '%s & %d & (%d) & & %d & (%d) & \\textbf{%.3f} \\\\ \n',cell_icd9{i,1}, ...
            cell_icd9{i,2}(1), round(cell_icd9{i,2}(2)), ...
            cell_icd9{i,3}(1), round(cell_icd9{i,3}(2)), ...
            cell_icd9{i,4});
    else
        fprintf(FID, '%s & %d & (%d) & & %d & (%d) & %.3f \\\\ \n',cell_icd9{i,1}, ...
            cell_icd9{i,2}(1), round(cell_icd9{i,2}(2)), ...
            cell_icd9{i,3}(1), round(cell_icd9{i,3}(2)), ...
            cell_icd9{i,4});
    end
end

fprintf(FID, '\\hline\n');


% elixhauser = {'CM_DIABETES','CM_CHF','CM_ALCOHOL_ABUSE','CM_ARRHYTHMIAS',...
%     'CM_VALVULAR_DISEASE','CM_HYPERTENSION','CM_RENAL_FAILURE','CM_CHRONIC_PULMONARY',...
%     'CM_LIVER_DISEASE','CM_CANCER','CM_PSYCHOSIS','CM_DEPRESSION'};
fprintf(FID, 'Elixhauser Comorbidity: & & & & & & \\\\ \n');
for i = 1 : size(cell_elix)
    if cell_elix{i,2}(1) == 0 && cell_elix{i,3}(1) == 0
        fprintf(FID, '%s & 0 & (0) & & 0 & (0) & NA \\\\ \n',cell_elix{i,1});
    elseif cell_elix{i,4} < 0.001
        fprintf(FID, '%s & %d & (%d) & & %d & (%d) & $\\mathbf{<0.001}$ \\\\ \n',cell_elix{i,1}, ...
            cell_elix{i,2}(1), round(cell_elix{i,2}(2)), ...
            cell_elix{i,3}(1), round(cell_elix{i,3}(2)));
    elseif cell_elix{i,4} < 0.05
        fprintf(FID, '%s & %d & (%d) & & %d & (%d) & \\textbf{%.3f} \\\\ \n',cell_elix{i,1}, ...
            cell_elix{i,2}(1), round(cell_elix{i,2}(2)), ...
            cell_elix{i,3}(1), round(cell_elix{i,3}(2)), ...
            cell_elix{i,4});
    else
        fprintf(FID, '%s & %d & (%d) & & %d & (%d) & %.3f \\\\ \n',cell_elix{i,1}, ...
            cell_elix{i,2}(1), round(cell_elix{i,2}(2)), ...
            cell_elix{i,3}(1), round(cell_elix{i,3}(2)), ...
            cell_elix{i,4});
    end
end

fprintf(FID, '\\bottomrule\n');
fprintf(FID, '\\end{tabular}\n');
fprintf(FID, '}\n');
fclose(FID);
